### ISSUE TITLE
No registered env

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark-ml#124]
the output about the exception as follow:
```
(venv) tinmode@tinmode-Precision-7920-Tower:~/bark-ml-build_package$ bazel run //examples:iqn -- --mode=train
INFO: Analyzed target //examples:iqn (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //examples:iqn up-to-date:
  bazel-bin/examples/iqn
INFO: Elapsed time: 0.224s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //examples:iqn
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tinmode/bark-ml-build_package/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/gym/envs/registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'highway-v1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/iqn.runfiles/bark_ml/examples/iqn.py", line 57, in <module>
    app.run(run_configuration)
  File "/home/tinmode/bark-ml-build_package/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/tinmode/bark-ml-build_package/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/iqn.runfiles/bark_ml/examples/iqn.py", line 37, in run_configuration
    env = gym.make(FLAGS.env, params=params)
  File "/home/tinmode/bark-ml-build_package/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/tinmode/bark-ml-build_package/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/home/tinmode/bark-ml-build_package/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: highway-v1
```
I can't get it, maybe you could show me the right way to solve it.

**Comment by patrickhart** [comment]
`highway-v1` is the discrete environment of BARK. 

Tests can be found here: https://github.com/bark-simulator/bark-ml/blob/e8e5eae4b6e512f39d7306b3f3374611669a0f33/bark_ml/tests/py_environment_tests.py#L43

An example here: https://github.com/bark-simulator/bark-ml/blob/master/examples/discrete_env.py

For me it is working locally.

**Comment by tinmodeHuang** [comment]
although discrete_env.py works well, some examples fail while doing tests with the command ```bazel test //...```.
```
INFO: Build completed, 12 tests FAILED, 337 total actions
//bark_ml:pip_package                                           (cached) PASSED in 0.2s
//bark_ml:py_tests                                              (cached) PASSED in 0.3s
//bark_ml/tests:py_behavior_tests                               (cached) PASSED in 0.8s
//bark_ml/tests:py_evaluator_tests                              (cached) PASSED in 6.2s
//bark_ml/tests:py_graph_observer_tests                         (cached) PASSED in 14.2s
//bark_ml/tests:py_observer_tests                               (cached) PASSED in 5.5s
//examples:blueprint_config                                     (cached) PASSED in 7.3s
//examples:continuous_env                                       (cached) PASSED in 3.5s
//experiments:py_experiment_tests                               (cached) PASSED in 4.5s
//bark_ml/tests:py_bark_behavior_model_tests                             PASSED in 12.3s
//examples:discrete_env                                                  PASSED in 2.7s
//bark_ml/tests:py_environment_tests                                     FAILED in 6.9s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/bark_ml/tests/py_environment_tests/test.log
//bark_ml/tests:py_graph_nets_tests                                      FAILED in 4.7s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/bark_ml/tests/py_graph_nets_tests/test.log
//bark_ml/tests:py_library_tfa_tests                                     FAILED in 10.9s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/bark_ml/tests/py_library_tfa_tests/test.log
//bark_ml/tests:py_library_torch_agents_tests                            FAILED in 1.4s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/bark_ml/tests/py_library_torch_agents_tests/test.log
//bark_ml/tests:py_tracer_tests                                          FAILED in 8.5s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/bark_ml/tests/py_tracer_tests/test.log
//examples:diadem_dqn                                                    FAILED in 2.1s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/examples/diadem_dqn/test.log
//examples:fqf                                                           FAILED in 3.1s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/examples/fqf/test.log
//examples:iqn                                                           FAILED in 1.9s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/examples/iqn/test.log
//examples:qrdqn                                                         FAILED in 3.0s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/examples/qrdqn/test.log
//examples:tfa                                                           FAILED in 8.5s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/examples/tfa/test.log
//examples:tfa_counterfactual                                            FAILED in 7.0s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/examples/tfa_counterfactual/test.log
//examples:tfa_gnn                                                       FAILED in 8.7s
  /home/tinmode/.cache/bazel/_bazel_tinmode/7e3363abb0cc39a8599a6c827d503a7a/execroot/bark_ml/bazel-out/k8-fastbuild/testlogs/examples/tfa_gnn/test.log

Executed 14 out of 23 tests: 11 tests pass and 12 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones thesINFO: Build completed, 12 tests FAILED, 337 total actions
```

**Comment by patrickhart** [comment]
Many of them might time-out. We defined test groups for bark-ml. E.g., try running ‘bazel test //bark_ml:unit_tests’

**Comment by tinmodeHuang** [comment]
```
(venv) tinmode@tinmode-Precision-7920-Tower:~/bark-ml-build_package$ bazel test //bark_ml/tests:py_environment_tests
INFO: Analyzed target //bark_ml/tests:py_environment_tests (96 packages loaded, 11053 targets configured).
INFO: Found 1 test target...
Target //bark_ml/tests:py_environment_tests up-to-date:
  bazel-bin/bark_ml/tests/py_environment_tests
INFO: Elapsed time: 20.273s, Critical Path: 16.22s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed successfully, 2 total actions
//bark_ml/tests:py_environment_tests                                     PASSED in 15.9s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 2 total actions
```

**Comment by NathanGavenski** [comment]
I'm having the same issue when trying to run `iqn.py` example.
@tinmodeHuang did you had any luck with that?
