### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by LDJ20210926** [bark-simulator/bark-ml#130]
Starting local Bazel server and connecting to it...
INFO: Repository bark_project instantiated at:
  D:/miniconda3/envs/reinfolab/lib/site-packages/bark-ml-master/WORKSPACE:5:21: in <toplevel>
  D:/miniconda3/envs/reinfolab/lib/site-packages/bark-ml-master/utils/dependencies.bzl:10:9: in bark_ml_dependencies
  D:/miniconda3/envs/reinfolab/lib/site-packages/bark-ml-master/utils/dependencies.bzl:7:14: in _maybe
Repository rule git_repository defined at:
  C:/users/huawei/_bazel_huawei/rdr3z4cz/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bark_project':
   Traceback (most recent call last):
        File "C:/users/huawei/_bazel_huawei/rdr3z4cz/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "C:/users/huawei/_bazel_huawei/rdr3z4cz/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "C:/users/huawei/_bazel_huawei/rdr3z4cz/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)

**Comment by patrickhart** [comment]
It seems like that there is an issue with BARK as dependency. Try `bazel clean --expunge` to clean bazel.
If not, you can also change the BARK version here: https://github.com/bark-simulator/bark-ml/blob/4cb81e2768e6ac6cf2e6999baf9b09bbca8115b3/utils/dependencies.bzl#L13

E.g. instead of using `commit = xxx`, you can also set `branch="master"`.

**Comment by LDJ20210926** [comment]
according to your method,I changed  the version,but still never worked.
here is the error:
D:\miniconda3\envs\reinfolab\python.exe -u bazelisk.py build -c opt //bark_ml:pip_package --verbose_failures --copt=/d2FH4-
Traceback (most recent call last):
  File "bazelisk.py", line 362, in <module>
    sys.exit(main())
  File "bazelisk.py", line 358, in main
    return execute_bazel(get_bazel_path(), argv[1:])
  File "bazelisk.py", line 346, in get_bazel_path
    bazelisk_directory, bazel_version)
  File "bazelisk.py", line 122, in resolve_version_label_to_number_or_commit
    history = get_version_history(bazelisk_directory)
  File "bazelisk.py", line 174, in get_version_history
    for release in get_releases_json(bazelisk_directory)
  File "bazelisk.py", line 150, in get_releases_json
    "https://api.github.com/repos/bazelbuild/bazel/releases")
  File "bazelisk.py", line 162, in read_remote_text_file
    with closing(urlopen(url)) as res:
  File "D:\miniconda3\envs\reinfolab\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\miniconda3\envs\reinfolab\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\miniconda3\envs\reinfolab\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\miniconda3\envs\reinfolab\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "D:\miniconda3\envs\reinfolab\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\miniconda3\envs\reinfolab\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
error: command 'D:\\miniconda3\\envs\\reinfolab\\python.exe' failed with exit status 1

**Comment by LDJ20210926** [comment]
I want to know whether  I need to have a bazel compilation environment，in the reality, I just have python env,and jupyter notebook to write codes,and VS.

**Comment by patrickhart** [comment]
You can also install bark as package using PyPI. If you have a matching operating system and Python environment there should be no re-compilation (by basilisk). So you could simply try to use `pip install bark-simulator`. However, new C++ functions cannot be integrated like this as a bazel compilation is required.

**Comment by LDJ20210926** [comment]
never work if  I just use pip install bark-ml, and last time, I tried to use off-line to install,so it reported the error as I ported as bellow.

**Comment by klemense1** [comment]
If you tried it using pip install bark-ml and it still tries to build it from source, your system might be outdated. Try `pip install --upgrade pip` to upgrade pip.

**Comment by patrickhart** [comment]
> never work if I just use pip install bark-ml, and last time, I tried to use off-line to install,so it reported the error as I ported as bellow.

Which version of Python are you using and which operating system? With Ubuntu and Python 3.7/3.8 it should work.

**Comment by LDJ20210926** [comment]
Maybe the problem is not here！If I use pip install bark-ml, there exists the problem as following:
ERROR: Failed building wheel for bark-simulator
ERROR: Failed building wheel for bark-ml
I don’t know where the problem is, it might be better if there is a XXX.wheel 
My operate system is windows10,and the python 3.7.6.
Mybe I can try it on Centos.

**Comment by patrickhart** [comment]
There are no wheels built for windows at the moment. Wheels are only available for Linux (using many wheels) and macOS. Using CentOS should work.

**Comment by patrickhart** [comment]
Also, I wold suggest you to have a look on the running Google CoLab example: https://colab.research.google.com/drive/1jA5QPEHadvIU6GsCy4cFdAv3giS7QvDQ?usp=sharing#scrollTo=j7GPSYfIOqru
