### ISSUE TITLE
draw a circle with specific radius and ego agent as center

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark-ml#91]
the modification was done in order to draw a circle of the radius specified with```params["ML"]["GraphObserver"]["VisibilityRadius"]```
```python
class BaseViewer(Viewer):
    def __init__(self, params=None, **kwargs):
        if(params is None):
            print("None") # ---------added afterwards
            params = ParameterServer()
        Viewer.__init__(self)
        # color parameters
        # agents
        self.color_other_agents_line = params["Visualization"]["Agents"]["Color"]["Other"]["Lines",
                                                                                           "Color of other agents", (0.1, 0.1, 0.1)]
...
        self.parameters = params
...
        # --------added afterwards
        self.radius = self.parameters["ML"]["GraphObserver"]["VisibilityRadius"]
        print(self.radius)
        if isinstance(self.radius, float):
            print("radius is of type float")
        elif isinstance(self.radius, ParameterServer):
            print("radius is of type ParameterServer")
        # ---------added afterwards
```
but the error happened when ran ```tfa_gnn.py```in bark-ml
```bash
<bark.runtime.commons.parameters.ParameterServer object at 0x7f2816b640b0>
radius is of type ParameterServer
<bark.runtime.commons.parameters.ParameterServer object at 0x7f27f01c8a70> <bark.runtime.commons.parameters.ParameterServer object at 0x7f27f01c8950>
Traceback (most recent call last):
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/examples/tfa_gnn.py", line 103, in <module>
    app.run(run_configuration)
...

  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/bark_ml/observers/graph_observer.py", line 122, in Observe
    radius=self._visibility_radius)
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/bark_ml/observers/graph_observer.py", line 354, in _nearby_agents
    if distance <= radius:
TypeError: '<=' not supported between instances of 'float' and 'ParameterServer'
```
I wonder what causes the error

**Comment by patrickhart** [comment]
That means that `self.parameters["ML"]["GraphObserver"]["VisibilityRadius"]` itself holds a `ParameterServer`.

How and where do you define the radius? You could try to use: 
```
        self.radius = self.parameters["ML"]["GraphObserver"]["VisibilityRadius", "Visibility radius.", 5.]
```

**Comment by tinmodeHuang** [comment]
params["ML"]["GraphObserver"]["VisibilityRadius"] is defined in```examples/example_params/tfa_sac_gnn_tf2_gnn_default.json``` where the items about ```Visualization``` were also defined and used to ```BaseViewer```which can be seen from the figure displayed

**Comment by patrickhart** [comment]
You can also save the loaded `ParameterServer` to see all variables that have been loaded and their structure:
`params.Save("written_param_test.json")`
It seems to me that `params["ML"]["GraphObserver"]["VisibilityRadius"]` holds another `ParameterServer`
